### ISSUE TITLE
It can not work unless I type ":setf cpp.root"

### ISSUE THREAD

**Issue by leeyeel** [parnmatt/vim-root#5]
Scientific Linux 7.1 and Vundle was used. It can not recognize "_.c/_.cpp/*.C" typefile unless I type :setfiletype cpp.root . I have set "filetype on and syntax enable" in my .vimrc file.  Any advice ?

**Comment by parnmatt** [comment]
If I am understanding you correctly, this is exactly the intended behaviour.

You do not want `.c`, `.cc` `.C`, `.cpp`, `.cxx`, `.h`, `.hh`, `.H`, `.hpp`, `.hxx`, *etc.* to *always* be associated with C++/ROOT, as users *also* could be writing in pure C or C++.

By similar logic, PyROOT users usually also write in pure Python.

I had written updated documentation to be clearer, but it was sitting in develop for a while. I just pushed `v1.0.1` which has these documentation changes.

Due to plugin conflicts that require absolute filetypes, and this only uses syntax currently, the safest and preferred way to use:

```VimL
:se syn+=.root
```

However, if you *really* want this is be used for all C-like files, add this to your `.vimrc` in your `autocmd` block (untested):

```VimL
autocmd filetype cpp setlocal syntax+=.root
```

if you do not have a `autocmd` block, you may wish to wrap them in this:
```VimL
if has("autocmd")
    autocmd!
    " above code
endif
```

**Comment by leeyeel** [comment]
Thanks a lot for your detailed explanation.
The problem  was still unsolved. Vim will show me error message if I use
 `autocmd filetype cpp setlocal syntax+=.root`.
 I tried to use
 `autocmd BufRead,BufNewFile *.c,*.cc,*.C :set filetype=cpp.root`
but it still not works..
It will work well  if  **root.vim** file was moved to **~/.vim/after/syntax/c.vim** .But I could not manager it by vundle .

**Comment by parnmatt** [comment]
Ok well it seems that you are using `*.c` for your ROOT code, which is not conventional, but still works so I only gave you half what you needed.
*the standard convention is to use `*.C` for ROOT unnamed macros, and `*.cxx` for named and code, however this doesn't matter*

I suggest using filetype detection to set syntax, not extensions to set filetypes, this might bite you in the arse later with other extentions

```VimL
if has("autocmd")
    autocmd!

    " always enable vim-root for C++/ROOT and PyROOT
    autocmd filetype c,cpp,python setlocal syntax+=.root

    " ... rest of your autocmd block
end if
```

I have tested this and it works, I also tested what I had given you previously and it also works, which is likely you typed it wrong and had a syntax error; but without you giving me the exact error I cannot confirm. I also tested your `autocmd` (*you do not need the `:` in a vimrc*) --- It also worked for me.

If the above code doesn't work you *need* to send me the full error message.

**Comment by parnmatt** [comment]
I've just had a thought, assuming you didn't have a syntax error when typing it out.
Could you copy and paste this into a terminal, and give me the output; I just want to ensure you have autocommands compiled into vim.

```bash
vim --version | grep '^\s*[+-]' | sed 's/\s\+/\n/g' | grep 'syntax\|autocmd'
```

**Comment by leeyeel** [comment]
+syntax
+autocmd

**Comment by parnmatt** [comment]
damn, so that's not it; thanks.

Ok, well when you next can, can you test the above, if you get errors forward them to me. Use `:messages` if need be.


On a side note:
I also see you've forked the project, but have not push changes to github. Feel free to contribute and submit pull requests, however you should still consider using mine directly, unless you check occasionally to pull the new changes. Now this project has come back into my attention, I may implement some changes that I remember having a year a go.

**Comment by leeyeel** [comment]
OK.And I will test it on Ubuntu later.

**Comment by parnmatt** [comment]
@leeyeel any luck, still having trouble, or did https://github.com/parnmatt/vim-root/issues/5#issuecomment-244749591 solve it?
